### ISSUE TITLE
plugin includes old version of Jetty Runner plugin - 9.2.1.v20140609

### ISSUE THREAD

**Issue by michael-card** [scalatra/scalatra-sbt#27]
This plugin depends on an old version of the JettyRunner plugin, version 9.2.1.v20140609. This version is apparently incompatible with IntelliJ 2017.* although it works fine with releases up to and including 2016.3.

When you install the JettyRunner plugin in IntelliJ IDEA, even if you download the 9.2.1.v20140609 release (which shows up in IntelliJ as Jetty Runner v. 1.1.3), there seems to be a "collision" or problem with the JettyRunner that is part of the xsbt-web-plugin that is used by this plugin and this results in run-time errors like this when you try to run a Scalatra app using Jetty Runner:

    java.lang.NoSuchMethodError: scala.runtime.BooleanRef.create(Z)Lscala/runtime/BooleanRef;

Is there any way you can fix this, i.e. can you upgrade to the newest version of JettyRunner and release an updated version of your plugin?

NOTE: I tried fixing my build.sbt file to include this but it did not help:

containerLibs in Jetty := Seq("org.eclipse.jetty" % "jetty-runner" % "9.2.1.v20140609" intransitive())

-Mike Card

**Comment by xpe** [comment]
Hello, could anyone share either (or both): a workaround? A fork?

**Comment by xpe** [comment]
Here is a solution that works for me.

In `project/plugins`, I have both:

```
addSbtPlugin("org.scalatra.sbt" % "scalatra-sbt" % "0.5.1")
addSbtPlugin("com.earldouglas" % "xsbt-web-plugin" % "3.0.3")
```

In `build.sbt`, I have:

```
import org.scalatra.sbt._
val ScalatraVersion = "2.5.1"
ScalatraPlugin.scalatraSettings
// ... 
libraryDependencies ++= Seq(
  // ... 
  "javax.servlet" % "javax.servlet-api" % "3.1.0" % "provided",
  "org.eclipse.jetty" % "jetty-webapp" % "9.4.6.v20170531" % "container",
  "org.scalatra" %% "scalatra" % ScalatraVersion,
  // ... 
)
containerLibs in Jetty := Seq(
  "org.eclipse.jetty" % "jetty-runner" % "9.4.6.v20170531" intransitive()
)
enablePlugins(JettyPlugin)
```

**Comment by xpe** [comment]
The above is documented at:
https://github.com/earldouglas/xsbt-web-plugin/blob/master/docs/2.3.md

In my opinion, this issue can be closed.

**Comment by takezoe** [comment]
@xpe Thanks for your support!

The latest xsb-web-plugin seems to use 9.4.1. Maybe we should update it if it's possible.
